<a href="https://colab.research.google.com/github/IBM-EPBL/IBM-Project-9714-1659069446/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Python

## 1. Split this string

In [5]:
s = "Hi there Sam!"

In [6]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742

In [8]:
planet="Earth"
diameter=12427
print(f"The diameter of the earth is {diameter}kilometers")

The diameter of the earth is 12427kilometers


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
display=d["k1"][3]["tricky"][3]["target"][3]
print(display)

hello


# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [18]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [14]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
x=np.arange(9)
x
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd


In [23]:
d={"Name":['koks','naf','kavi'],
   "Age":[20,21,22]}
d1=pd.DataFrame(d)
d1

Name  Age
0  koks   20
1   naf   21
2  kavi   22

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [22]:
import datetime
start = datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
end = datetime.datetime.strptime("01-01-2023","%d-%m-%Y")
x = pd.date_range(start,end)
x

DatetimeIndex(['2023-01-01'], dtype='datetime64[ns]', freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [20]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]